# Generated by Django 5.1.7 on 2025-03-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_opportunite', models.CharField(max_length=50, unique=True)),
                ('nom_client', models.CharField(max_length=255)),
                ('tarif_propose', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
