# Generated by Django 5.1.7 on 2025-03-28 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('rue', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DevisExtended',
            fields=[
                ('devis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devis.devis')),
            ],
            bases=('devis.devis',),
        ),
        migrations.AddField(
            model_name='devis',
            name='client_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devis',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='presence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devis',
            name='rcmo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devis',
            name='taux_do',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='taux_trc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_bien',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_garantie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='type_travaux',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devis.adresse'),
        ),
    ]
