# Generated by Django 5.1.7 on 2025-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_adresse_devisextended_devis_client_vip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='code_postal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='rue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='ville',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
