# Generated by Django 5.1.7 on 2025-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_alter_adresse_code_postal_alter_adresse_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='tarif_propose',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='devis',
            name='taux_do',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='taux_trc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
