# Generated by Django 5.1.7 on 2025-03-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0004_alter_devis_tarif_propose_alter_devis_taux_do_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevisExtended',
        ),
    ]
